### ISSUE TITLE
IMOOC 的 前端 sublime 课程

### ISSUE THREAD

**Issue by happypeter** [happypeter/happysublime#12]
http://www.imooc.com/learn/40

**Comment by happypeter** [comment]
讲得很流畅很实用，但是基础部分很多都没有讲。如何全局查找，如何自定制 snippet ，绑定快捷键。

emmet，行操作等基本操作，要知道很多人的 sublime 是他们第一个编辑器。

分屏。

**Comment by happypeter** [comment]
刚才跟亮亮沟通了一下，他表示可以开始做我这门课了，避免一下跟人家这门课的内容重叠就好了。

**Comment by tomener** [comment]
怎么把删了
